// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RazorPages.Models;
using System;

namespace RazorPages.Migrations
{
    [DbContext(typeof(DogContext))]
    [Migration("20180412115558_Cat")]
    partial class Cat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorPages.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birth");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Sex")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Cat");
                });

            modelBuilder.Entity("RazorPages.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birth");

                    b.Property<int?>("CatId");

                    b.Property<int?>("Height");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Sex")
                        .IsRequired();

                    b.Property<int?>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("RazorPages.Models.Dog", b =>
                {
                    b.HasOne("RazorPages.Models.Cat", "Cat")
                        .WithMany()
                        .HasForeignKey("CatId");
                });
#pragma warning restore 612, 618
        }
    }
}
